CREATE TABLE [dbo].[MasterTable]
(
	[Id] INT NOT NULL PRIMARY KEY, 
    [SomeText] NVARCHAR(50) NOT NULL, 
    [Feature1Column] NVARCHAR(50) NOT NULL, 
    [Created] DATETIME2 NULL DEFAULT SYSDATETIME()
)
